Update OptionParser.php
spec option with optionnal value output fatal error when value(s) missing

$specs->add('z|zoo?', 'option with optional value.');

Fatal error: Call to a member function isEmpty() on null in \vendor\corneltek\getoptionkit\src\GetOptionKit\OptionParser.php on line 74
Fatal error: Call to a member function isOption() on null in \vendor\corneltek\getoptionkit\src\GetOptionKit\OptionParser.php on line 201